Feature
YASUO0715/meal_app pull request #1
Opened 2021-10-12 07:24 UTC by YASUO0715

2021-10-12 11:46 UTC, kazu-taka requested changes
@YASUO0715 
コメントしたので確認お願いします:bow:

2021-10-12 11:46 UTC, kazu-taka commented on meal_app/README.md
> +* Likesable・・・poststable,Userstableへの外部キーあり
@YASUO0715 
スネークケースとキャメルケースが混在しているので、`categories`テーブル、`posts`テーブル、`likes`テーブルの表現がいいのかなと思いました！

2021-10-12 11:46 UTC, kazu-taka commented on meal_app/app/Http/Controllers/LikeController.php
> +        return back();
@YASUO0715 
戻る画面が一つだけだと思うので、backは使用せず、指定の画面にリダイレクトするように修正して下さい！
unlikeも同様です！

2021-10-12 11:46 UTC, kazu-taka commented on meal_app/app/Http/Controllers/PostController.php
> +        // $post = new Category($request->all());
@YASUO0715 
不要なコードは削除して下さい✨
他の部分も見直しお願いします！

2021-10-12 11:46 UTC, kazu-taka commented on meal_app/database/factories/PostFactory.php
> +            'user_id' => Arr::random(Arr::pluck(User::All(), 'id')),
@YASUO0715 
Eloquentを使用してランダムなデータを取得する場合は、inRandomOrderメソッドがおすすめです！
時間があるので使ってみて下さい✨
https://webty.jp/staffblog/production/post-2184/

2021-10-12 11:46 UTC, kazu-taka commented on meal_app/database/migrations/2021_10_10_174143_create_likes_table.php
> +            $table->unsignedBigInteger('user_id')->nullable();
@YASUO0715 
nullを許可した理由を教えて下さい🙏

2021-10-12 11:46 UTC, kazu-taka commented on meal_app/resources/views/posts/create.blade.php
> +        @endif
@YASUO0715 
editでも使用しているので、コンポーネントとして共通化して下さい✨

2021-10-12 11:46 UTC, kazu-taka commented on meal_app/resources/views/posts/show.blade.php
> +@endif
@YASUO0715 
インデントの修正をお願いします！！

2021-10-12 11:46 UTC, kazu-taka commented on meal_app/routes/web.php
> +Route::get('/reply/unlike/{post}', [LikeController::class, 'unlike'])->name('unlike');
@YASUO0715 
いいねはpostsに必ず紐付いているので、ルーティングはネスト(postsの中にlikesがある)させるようにして下さい👍
またrestfulなURLにした方が良いので、unlinkではなく、resourceを使用して、storeがいいね、destroyがいいねの問r消しになるようにしてください！

2021-10-13 04:39 UTC, YASUO0715 commented on meal_app/routes/web.php
> +Route::get('/reply/unlike/{post}', [LikeController::class, 'unlike'])->name('unlike');
@kazu-taka 
各指摘事項を修正いたしました。
ご確認のほど宜しくお願い致します。

2021-10-13 06:36 UTC, kazu-taka requested changes
@YASUO0715 
コメントしたので修正お願いします:bow:

2021-10-13 06:36 UTC, kazu-taka commented on meal_app/README.md
> +* Likesテーブル・・・poststable,Userstableへの外部キーあり
@YASUO0715 
こちらの修正が不十分でした^^;
TablePlusで見て頂くと分かりますが、テーブル名は 全て小文字になるので、`posts`や`likes`でお願いします！

2021-10-13 06:36 UTC, kazu-taka commented on meal_app/database/factories/PostFactory.php
> +            'user_id' => optional(User::inRandomOrder()->first())->id,
@YASUO0715 
user_idはnullが入ってはいけないところ(nullは登録できない)なので、optionalを使用しなくても良いです✨
usersテーブルにデータが存在しない時にエラーが発生する場合は、エラーが起きないように先にusersテーブルにデータを作るようにして下さい👍

2021-10-13 06:36 UTC, kazu-taka commented on meal_app/database/migrations/2021_10_10_174143_create_likes_table.php
> +            $table->unsignedBigInteger('user_id');
@YASUO0715 
ここはnullを取るだけではなく、外部キーにした方が良いので、foreingnIdを使用するようにして下さい😊

2021-10-13 06:36 UTC, kazu-taka commented on meal_app/routes/web.php
> +    ->only(['store', 'destroy']);
@YASUO0715 
ログインしていなくても外部から削除や登録される恐れがあるので、認証済みの時だけアクセスできるように修正お願いします！

2021-10-13 12:06 UTC, kazu-taka requested changes
@YASUO0715 
コメントしたので、確認と修正後マージしてOKです👍

2021-10-13 12:06 UTC, kazu-taka commented on meal_app/database/factories/PostFactory.php
> +            'user_id' => (User::inRandomOrder()->first())->id,
@YASUO0715 
括弧を取って、`User::inRandomOrder()->first()->id,`でも大丈夫だと思います！

2021-10-13 12:06 UTC, kazu-taka commented on meal_app/database/migrations/2021_10_10_174143_create_likes_table.php
> +                ->cascadeOnDelete();
@YASUO0715 
不要なコメントの削除をインデントの修正をお願いします:bow:

2021-10-13 12:06 UTC, kazu-taka commented on meal_app/routes/web.php
> +use GuzzleHttp\Middleware;
@YASUO0715 
このクラスは必要ですか！？😅

2021-10-14 03:09 UTC, YASUO0715 commented
@kazu-taka 
お忙しいところ何度もご確認ありがとうございました。
修正致します。

2021-10-14 04:57 UTC, kazu-taka commented
@YASUO0715 
全然申し訳なくないです！！
あと2万回チェック可能です👍

2021-10-15 00:10 UTC, merged